name: Flutter Build

on:
  push

jobs:
  windows:
    runs-on: windows-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2x

      - name: Flutter Windows Build
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows

      # Commit
      - name: Update Flutter Web 
        uses: stefanzweifel/git-auto-commit-action@v4.2.0
        with:
          commit_message: Update Build Files

  web:
    # Ubuntus
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2x

      - name: Flutter Setup
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.5'

      - name: Flutter Web Build
        run: |
          flutter pub get
          flutter build web
          rm -rf ./docs
          mv -fv ./build/web ./docs

      # Commit
      - name: Update Flutter Web 
        uses: stefanzweifel/git-auto-commit-action@v4.2.0
        with:
          commit_message: Update Build Files

      # Slack
  slack_notification:
    if: always()
    needs: publish
    runs-on: ubuntu-latest
      - name: Slack Notification
        if: success()
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: Flutter Build
          attachments: |
            [
              {
                "color": "good",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "fields": [
                  {
                    "title": "Push Repository",
                    "value": "${{ github.event.repository.url }}"
                  }, 
                  {
                    "title": "Pusb Branch",
                    "value": "${{ github.ref }}"
                  }, 
                  {
                    "title": "Commit Message",
                    "value": "${{ github.event.head_commit.message }}"
                  }
                ]
              }
            ]
