name: Flutter Build

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: echo "windows"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "ubuntu"
  publish:
    runs-on: macos-latest
    needs: test
    steps:
      - run: echo "macos"